### ISSUE TITLE
Make new functions examples

### ISSUE THREAD

**Issue by danielsolartech** [sflynlang/compiler#13]
To write a new example you don't need compile the code, just need see the following examples:

[Functions Sflynlang documentation](https://github.com/sflynlang/compiler/wiki/Functions-and-Anonymous-Functions)

[Callback Example](https://github.com/sflynlang/compiler/blob/main/examples/functions/callback.sf)

[Double a number Example](https://github.com/sflynlang/compiler/blob/main/examples/functions/double.sf)

[Less or Greater Example](https://github.com/sflynlang/compiler/blob/main/examples/functions/less_or_greater.sf)

[Say Hi Function Example](https://github.com/sflynlang/compiler/blob/main/examples/functions/say_hi.sf)

**Comment by dantehemerson** [comment]
Can I take this?

**Comment by danielsolartech** [comment]
Yes, you can, @dantehemerson :D
