### ISSUE TITLE
Syntax or orthographic corrections [EN]

### ISSUE THREAD

**Issue by danielsolartech** [sflynlang/compiler#15]
I'm not a native english speaker and i can get mistakes in any moment, so if you find one in the documentation of the repository you can send a pull request changing it to a best way.

## Files
- [ ] [Wiki Home Page](https://github.com/sflynlang/compiler/wiki)
- [ ] [Wiki Functions and Anonymous Functions](https://github.com/sflynlang/compiler/wiki/Functions-and-Anonymous-Functions)
- [ ] [Wiki Interfaces and Methods](https://github.com/sflynlang/compiler/wiki/Interfaces-and-HashMaps)
- [ ] [Wiki Variables](https://github.com/sflynlang/compiler/wiki/Variables)

**Comment by hanyangl** [comment]
@danielsolartech you can assign this to me too.

**Comment by danielsolartech** [comment]
@hanyangl ready

**Comment by hanyangl** [comment]
I will submit PR in October as part of hacktober

**Comment by danielsolartech** [comment]
@hanyangl is okey :D, happy hacktoberfest!

**Comment by hanyangl** [comment]
reviewed. https://github.com/sflynlang/compiler/pull/17
